spring:
  application:
    name: bts

  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
    url: ${SUPABASE_DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SUPABASE_DB_USERNAME}
    password: ${SUPABASE_DB_PASSWORD}

  h2:
    console:
      enabled: true
      path: /h2-console


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SUPABASE_JWT_ISSUER}
          jwk-set-uri: ${SUPABASE_JWT_JWKS_URI}

  config:
    import: optional:file:.env[.properties] # .env파일에서 환경변수 로드

server:
  port: 8080


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

seoul:
  open-api:
    key: ${SEOUL_OPEN_API_KEY}

google:
  translation:
    api:
      key: ${GOOGLE_TRANSLATION_API_KEY}